stages:
 - build
 - test
 - deploy
 - codeOwners_Permissions

before_script:
 - echo "Running global before script..."

variables:
 GIT_SUBMODULE_STRATEGY: recursive
 GREEN: '\033[1;32m'
 RED: '\033[1;31m'
 NC: '\033[0m'

.only-default: &only-default
  only:
    - merge_requests
    - dev
    - tags

codeOwners:
    image: git.jinr.ru:5005/nica/nicadist/c7:alibuild-dev
    stage: codeOwners_Permissions
    dependencies: []
    tags:
      - cvmfs
    before_script:
      - source /etc/bashrc
    only:
        refs:
            - merge_requests
        variables:
            - $CI_MERGE_REQUEST_PROJECT_PATH == "nica/mpdroot" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"
    script:
        - module add Clang
        - scripts/inform_codeowners.sh
        - scripts/check_clangFormatting.sh

check_permissions:
  image: git.jinr.ru:5005/nica/nicadist/c7:alibuild-dev
  dependencies: []
  variables:
    OS_TYPE: "centos7"
    PERMISSIONS_MESSAGE_FAILURE: "Permissions check: ${RED}FAILED${NC}. You don't have permission to change some files, please contact your project maintainers."
    PERMISSIONS_MESSAGE_SUCCESS: "Permissions check: ${GREEN}PASSED${NC}."
  before_script:
    - echo "Skipping global before_script"
  tags:
    - docker
  stage: codeOwners_Permissions
  script:
    - >
      if git diff HEAD~ --name-only|grep .gitlab-ci.yml; then
        if grep -q $GITLAB_USER_LOGIN <<< $MAINTAINERS; then echo -e $PERMISSIONS_MESSAGE_SUCCESS $(exit 0); else echo -e $PERMISSIONS_MESSAGE_FAILURE; $(exit -1); fi
      fi;
  allow_failure: false
  <<: *only-default

# nicadist images and execution of new pipelines 
# cannot place into separate .yml file, due to ongoing mutation of Gitlab parsing bug 5078
.build_template: &build
  image: git.jinr.ru:5005/nica/nicadist/$OS_TYPE:alibuild-dev
  stage: build
  before_script:
    - source /etc/bashrc
    - export NPROC=$(cat /proc/cpuinfo | grep processor | wc -l)
  script:
    - export MPDROOT=$(readlink -m $OS_TYPE/mpdroot)
    - module add mpddev/latest
    - mkdir build && cd build && cmake ..
    - make install -j $NPROC
  artifacts:
    paths:
      - $OS_TYPE/mpdroot/
    expire_in: 2h
  tags:
    - cvmfs
  only:
    - merge_requests
  allow_failure: true
  <<: *only-default

build:c7:
  variables:
    OS_TYPE: "c7"
  <<: *build

.test_build_template: &build_tests
  image: git.jinr.ru:5005/nica/nicadist/$OS_TYPE:alibuild-dev
  stage: test
  before_script:
    - source /etc/bashrc
  script:
    - module add mpddev/latest
    - export MPDROOT=$(readlink -m $OS_TYPE/mpdroot)
    - source $MPDROOT/config/env.sh
    - $CI_PROJECT_DIR/scripts/run_build_tests.sh -r $REPORT_NAME
    - (if grep -q "failure" $REPORT_NAME.xml; then $(exit -1); else $(exit 0); fi);
  tags:
    - cvmfs
  only:
    - merge_requests
  artifacts:
    when: always
    reports:
      junit: $REPORT_NAME.xml
  allow_failure: true
  <<: *only-default

build_tests:c7:
  variables:
    OS_TYPE: "c7"
    REPORT_NAME: "report_c7"
  needs: ["build:c7"]
  dependencies:
    - build:c7
  retry: 1       # retry script if it failed (sometimes if fails due to some unexpected particle). Maximum 2 retries.
  <<: *build_tests

.deploy_template: &deploy
  stage: deploy
  before_script:
    - echo "Skipping global before_script"
  script:
    - scripts/trigger_nicadist.sh          # new deployment via nicabuild
  only:
    - tags
    - dev
  allow_failure: false

deploy:nicadist:
  image: git.jinr.ru:5005/nica/nicadist/c7:alibuild-dev
  tags:
    - docker
    - no-cvmfs
  <<: *deploy

pages:
  image: git.jinr.ru:5005/nica/docs/docs:latest
  stage: build
  before_script:
    - echo "Skipping global before_script"
  script:
    - scripts/build_docs.sh
  artifacts:
    paths:
    - "public"
  only:
    - dev
  allow_failure: false

