#! /bin/bash
#
# script to install FairSoft/FairRoot apr21 version
# the script creates directory "fair_build" where all sources/compilation are located
#
# takes two input parameters:
# 1. directory, where FairSoft/FairRoot will be installed
# 2. number of cpu threads used in compilation
#
# Example: ./install_fairApr21 ~/fairApr21 8
#
# IMPORTANT: -directory where script is executed cannot contain "fair_build" folder
#            -the script was tested to work under following conditions:
#             input parameter of target install directory located in $HOMEDIR,
#             the script was executed from $HOMEDIR.
#             If otherwise, make sure you have correct permissions !

# exit when any command fails
set -e

# assign input parameters to variables
fair_dir=$1
cpu_threads=$2
init_dir=$(pwd)

# create and enter working directory for build
work_dir=fair_build
mkdir $work_dir && cd $work_dir

# FairSoft build and install
git clone -b apr21p1 https://github.com/FairRootGroup/FairSoft
cd FairSoft && mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=$fair_dir/FairSoft -DGEANT4MT=OFF ..
make -j $cpu_threads
sed -i '/#include "UserDefaults.h"/a #include <thread>' Source/dds/dds-info/src/main.cpp
make -j $cpu_threads
sed -i '/#include <vector>/a #include <thread>' Source/fairmq/fairmq/sdk/DDSSession.cxx
sed -i 's/  int dummy;/  int dummy = 0;/g' Source/fairmq/extern/googletest/googletest/src/gtest-death-test.cc
sed -i 's/  bool result;/  bool result = false;/g' Source/fairmq/extern/googletest/googletest/src/gtest-death-test.cc
make -j $cpu_threads
cd $fair_dir/FairSoft/lib
ln -s libpythia6.so libPythia6.so
export SIMPATH=$fair_dir/FairSoft

# FairRoot build and install
cd $init_dir/$work_dir
git clone -b v18.6.4 https://github.com/FairRootGroup/FairRoot.git
cd FairRoot && mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=$fair_dir/FairRoot ..
make -j $cpu_threads
make install
