#! /bin/bash
#
# script to install MPDRoot
# tested to work as of 31.10.2021 
# after installing fair suite with install_fairApr21 script
#
# takes two input parameters:
# 1.--developer or --regular based on user type
# 2. number of cpu threads used in compilation
#
# Example: ./install_mpdroot --developer 8
#
# IMPORTANT: -the script was tested to work under following conditions:
#             the script was executed from $HOMEDIR after running
#             scripts/install_fairApr21 ~/fairApr21 8 from $HOMEDIR
#             If otherwise, make sure you have correct permissions !

# exit when any command fails
set -e

if [ "$1" == "--regular" ]; then
 git clone -b dev --recursive https://git.jinr.ru/nica/mpdroot.git
else 
 if [ "$1" == "--developer" ]; then
  git clone -b dev --recursive git@git.jinr.ru:nica/mpdroot.git 
 else
  echo "Only --regular or --developer allowed as first parameter! Terminating...\n"
  exit 1 
 fi
fi


# assign input parameters to variables
cpu_threads=$2

# linking with local Fair suite installation
cd mpdroot
sed -i 's/export SIMPATH=\/opt\/fairsoft\/install/export SIMPATH=~\/fairApr21\/FairSoft/g' SetEnv.sh
sed -i 's/export FAIRROOTPATH=\/opt\/fairroot\/install/export FAIRROOTPATH=~\/fairApr21\/FairRoot/g' SetEnv.sh
source SetEnv.sh

# prevent SetEnv.sh from being overwritten by future git synchronizations
git rm --cached SetEnv.sh

# create & enter local build directory. run cmake config
mkdir build && cd build && cmake ..

# build
make -j $cpu_threads

# source new configuration
source config.sh



