#!/bin/bash

# Git pre-commit hook
# Copy the script to .git/hooks and make it executable by running
# chmod u+x pre-commit
#
# Written for MPDRoot @JINR Dubna
# First commit Slavomir Hnatic, 11.2021

######################################################################
######################### Functionality ##############################
###                                                                ###
###    If there is a clang-format version match, then applies      ###
###    clang-format to all staged files with c++ file suffix       ###
###								   ###
###  IMPORTANT: Clang-format versions must be identical !!!        ###
###         (different versions might produce different results)   ###
###                                                                ###
######################################################################

REQUIRED_VERSION="13.0.0"
CLANG_FORMAT_BIN=$(command -v clang-format)
CLANG_STYLE=file

# if clang-format is installed, check if its version is correct
if [[ -n $CLANG_FORMAT_BIN ]]; then
 VERSION=$($CLANG_FORMAT_BIN --version | awk '{print $3}')
 if [[ $VERSION != $REQUIRED_VERSION ]]; then
  echo "Installed clang-format version ($VERSION) does not match required version ($REQUIRED_VERSION)!"
  CLANG_FORMAT_BIN=""
 fi
fi

# do the formatting, or ask the user to install required package
if [[ -n $CLANG_FORMAT_BIN ]]; then
 for FILE in $(git diff --cached --name-only | grep -E '.*\.(h|hpp|c|cpp|cxx)$' | grep -viE '.*LinkDef.h$'); do
  $CLANG_FORMAT_BIN -i --style=$CLANG_STYLE $FILE
 done
else
 echo
 echo " YOUR CHANGES CANNOT BE FORMATTED"
 echo
 echo " Please use clang-format version $REQUIRED_VERSION"
 echo " by adding mpddev module in the toolbox NICA container."
 echo
fi

